config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:index, :new, :create, :destroy]
  resources :event_attachments, only: [] do
    member do
      get :download
    end
  end

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'reports#index'

  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :sessions, only: [:index, :create, :destroy]
  resources :verboice_callbacks, only: [:index]
  resources :dashboards, only: [:index]
  resources :calendars, only: [:index]
  resources :weeks, only: [:index]
  resources :sms_recipients
  resources :places do
    collection do
      get 'ods_list'
      get 'download_template'
      post 'confirm_upload_location'
      post 'upload_location'
      get 'import'
      get 'download'
      get 'download_users'
    end
    member do
      put 'move'
    end
  end

  resources :users do
    collection do
      get 'profile'
      put 'change_profile'
      get 'download_template'
      post 'confirmed_upload_users'
      post 'upload_users'
      get 'by_place'
      get 'search'
      get 'import'
    end

    member do
      put 'reset'
    end
  end

  resources :settings, only: [:index] do
    collection do
      put 'update_report'
    end
  end

  put 'message_template' => 'settings#update_message_template'
  put 'update_settings' => 'settings#update_settings'
  put 'upsert_telegram_bot' => 'settings#upsert_telegram_bot'

  put 'verboice' => 'settings#verboice'
  put 'hub' => 'settings#hub'
  get 'project_variables' => 'settings#project_variables'
  get 'external' => 'settings#external'

  get '/steps/manifest' => 'steps#manifest', defaults: { format: :xml }
  resources :steps do
    collection do
      post :validate_hc_worker
      post :send_sms
      post :notify_reporting_started
      post :notify_reporting_ended
    end
  end

  resources :reports, only: [:index, :destroy] do
    member do
      put :toggle_status
      put :update_week
    end

    collection do
      get :export_as_csv
      get :query_piechart
    end
  end

  resources :report_variables, only: [] do
    member do
      get :play_audio
    end
  end

  resources :variables

  resources :channels do
    member do
      put 'state'
      put 'mark_as_default'
    end
  end

  resources :logs, only: [:index]

  resources :alert_settings

  resources :external_sms_settings
  resources :hub_push_notifications, only: [:create]

  resources :sms_broadcasts, only: [:index, :create]

  resources :weekly_place_reports, only: [:index]

  namespace :api, defaults: {format: 'json'} do
    resources :places, only: [:index]
    namespace :hub do
      resources :reports, only: [:index, :show]
    end
  end

  # Telegram
  telegram_webhook TelegramWebhooksController
  resource :help, only: [:show]
end

app/views/shared/_health_structure.html.erb
<%= breadcrumb [ {"Health Structure" => nil}] %>

<div class="inner-container">
  <div class="clearfix">
    <div class="pull-right" style='margin-top: 10px;'>
      <%=link_to download_places_path(format: :csv), class: 'btn btn-primary' do %>
        <i class="glyphicon glyphicon-download"> </i> Export Health Structure as CSV
      <% end %>

      <%=link_to download_users_places_path(format: :csv), class: 'btn btn-primary' do %>
        <i class="glyphicon glyphicon-download"> </i> Export User as CSV
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class='col-lg-4'>
      <%= render 'shared/search_user' %>
      <%= render 'shared/tree' %>
    </div>

    <div class="col-lg-8">
      <div>
        <span> Selected <i class='glyphicon glyphicon-play' style='font-size: 80%; color: gray; '> </i> </span>
        <span id='selected-tree' style='color: gray;'></span> </div>
      <div id='user-list'> <%= render 'users/list', users: users %> </div>
    </div>
  </div>
</div>

app/views/shared/_search_user.html.erb
<div class='' style='margin-bottom: 10px;'>
  <%= form_tag search_users_path, method: :get do %>
    <div class="input-group">
      <%= text_field_tag :phone, params[:phone], class: 'form-control', placeholder: 'Reporter phone number' %>
      <span class="input-group-btn">
        <button class="btn btn-primary" type="submit" id='btn-search-user'>
          <i class='glyphicon glyphicon-search'> </i> Search
        </button>
      </span>
    </div>
  <% end %>
</div>

app/views/shared/_tree.html.erb
<div class='tree-wrapper' >
  <ul id="myTree" data-toggle="nav-tree" >
    <%= tree_for(Place.arrange, @place_id) %>
   </ul>
</div>

<div class='tree-action clearfix' style='color: gray;' >
  <div class="pull-left" >
    <%= link_to "Import Health Structure", places_import_path(), :method => :get, :class => 'btn btn-primary to-right' %>
  </div>
  <div class='pull-right'>
    <%= link_to '#', class: 'new-tree' do %>
      <i class='glyphicon glyphicon-plus'> </i>
    <% end %>
    <%= link_edit '', '#', class: 'edit-tree' %>
    <%= link_destroy '', '#', class: 'destroy-tree', method: :delete %>
  </div>
</div>