config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:index, :new, :create, :destroy]
  resources :event_attachments, only: [] do
    member do
      get :download
    end
  end

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'reports#index'

  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :sessions, only: [:index, :create, :destroy]
  resources :verboice_callbacks, only: [:index]
  resources :dashboards, only: [:index]
  resources :calendars, only: [:index]
  resources :weeks, only: [:index]
  resources :sms_recipients
  resources :places do
    collection do
      get 'ods_list'
      get 'download_template'
      post 'confirm_upload_location'
      post 'upload_location'
      get 'import'
      get 'download'
      get 'download_users'
    end
    member do
      put 'move'
    end
  end

  resources :users do
    collection do
      get 'profile'
      put 'change_profile'
      get 'download_template'
      post 'confirmed_upload_users'
      post 'upload_users'
      get 'by_place'
      get 'search'
      get 'import'
    end

    member do
      put 'reset'
    end
  end

  resources :settings, only: [:index] do
    collection do
      put 'update_report'
    end
  end

  put 'message_template' => 'settings#update_message_template'
  put 'update_settings' => 'settings#update_settings'
  put 'upsert_telegram_bot' => 'settings#upsert_telegram_bot'

  put 'verboice' => 'settings#verboice'
  put 'hub' => 'settings#hub'
  get 'project_variables' => 'settings#project_variables'
  get 'external' => 'settings#external'

  get '/steps/manifest' => 'steps#manifest', defaults: { format: :xml }
  resources :steps do
    collection do
      post :validate_hc_worker
      post :send_sms
      post :notify_reporting_started
      post :notify_reporting_ended
    end
  end

  resources :reports, only: [:index, :destroy] do
    member do
      put :toggle_status
      put :update_week
    end

    collection do
      get :export_as_csv
      get :query_piechart
    end
  end

  resources :report_variables, only: [] do
    member do
      get :play_audio
    end
  end

  resources :variables

  resources :channels do
    member do
      put 'state'
      put 'mark_as_default'
    end
  end

  resources :logs, only: [:index]

  resources :alert_settings

  resources :external_sms_settings
  resources :hub_push_notifications, only: [:create]

  resources :sms_broadcasts, only: [:index, :create]

  resources :weekly_place_reports, only: [:index]

  namespace :api, defaults: {format: 'json'} do
    resources :places, only: [:index]
    namespace :hub do
      resources :reports, only: [:index, :show]
    end
  end

  # Telegram
  telegram_webhook TelegramWebhooksController
  resource :help, only: [:show]
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id         :integer          not null, primary key
#  var        :string(255)      not null
#  value      :text(65535)
#  thing_id   :integer
#  thing_type :string(30)
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_settings_on_thing_type_and_thing_id_and_var  (thing_type,thing_id,var) UNIQUE
#

class Setting < RailsSettings::CachedSettings
  VERBOICE = :verboice
  HUB = :hub
  ALERT = :alert
  REPORT = :report
  TEMPLATE = :template
  TELEGRAM_BOT = :telegram_bot

  def self.hub_enabled?
    ENV['HUB_ENABLED'].present? && ENV['HUB_ENABLED'].to_i == 1
  end

  def self.hub_configured?
    Setting[:hub_url].present? && Setting[:hub_email].present? && Setting[:hub_password].present? && Setting[:hub_task_name].present?
  end

  def self.exceptional_years
    ENV['EXCEPTIONAL_YEAR'].present? ? ENV['EXCEPTIONAL_YEAR'].split(",").map(&:strip) : []
  end

  def self.wkst
    ENV['WKST'].present? ? ENV['WKST'].to_i : 0
  end
  
  def self.number_of_revise_week_available
    ENV['NUM_OF_REVISE_WEEK'].present? ? ENV['NUM_OF_REVISE_WEEK'].to_i : 1
  end
end

app/models/setting/message_template_setting.rb
class Setting::MessageTemplateSetting
  attr_reader :enabled, :report_confirmation

  VARIABLES = %w(week_year reported_cases)

  def initialize options = { }
    @enabled = options[:enabled] || false
    @report_confirmation = options[:report_confirmation]
  end

  def enabled?
    enabled
  end

end

app/models/setting/report_setting.rb
class Setting::ReportSetting
  attr_reader :enables, :x_week, :recipient_types

  REPORTER_VARIABLES = %w(place_name last_reported x_week)
  SUPERVISOR_VARIABLES = %w(place_name x_week)

  def initialize options = { recipient_types: [] }
    @days = options[:days] || []
    @enables = options[:enables] || []
    @x_week = options[:x_week].to_i || 0
    @recipient_types = options[:recipient_types].reject(&:empty?) || []
  end

  def templates
    @templates || {}
  end

  def templates=(templates)
    @templates = {}

    templates.each do |k, v|
      # k can be sms, verboice, and telegram
      @templates[k] = "Setting::#{k.titlecase}TemplateSetting".constantize.new(v) if Alert::TYPES.keys.include?(k.to_sym)
    end
  end

  def has_day? wday
    @days.include?(wday.to_s)
  end

  def has_enabled?
    @enables.size > 0
  end

  def voice_enabled?
    @enables.include?(Alert::TYPES[:voice])
  end

  def sms_enabled?
    @enables.include?(Alert::TYPES[:sms])
  end

  def telegram_enabled?
    @enables.include?(Alert::TYPES[:telegram])
  end

  def has_week?
    @x_week > 0
  end

  def has_recipient? place_type
    recipient_types.include? place_type
  end

end

app/models/setting/sms_template_setting.rb
class Setting::SmsTemplateSetting
  attr_reader :reporter, :supervisor

  def initialize options = {}
    @reporter = options[:reporter_template] || ''
    @supervisor = options[:supervisor_template] || ''
  end
end

app/models/setting/telegram_template_setting.rb
class Setting::TelegramTemplateSetting
  attr_reader :reporter, :supervisor

  def initialize options = {}
    @reporter = options[:reporter_template] || ''
    @supervisor = options[:supervisor_template] || ''
  end
end

app/models/setting/voice_template_setting.rb
class Setting::VoiceTemplateSetting
  attr_reader :channel_id, :call_flow_id, :call_time

  def initialize options = {}
    @channel_id = options[:channel_id] || -1
    @call_flow_id = options[:call_flow_id] || -1
    @call_time = options[:call_time]
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  authorize_resource

  def index
    # to get all items for render list
    Setting[:project] = params[:project] if params[:project]
    @settings   = Setting.unscoped
    @parameters = verboice_parameters
    @variables  = Variable.where(verboice_project_id: Setting[:project])
    @alert_setting = AlertSetting.find_or_initialize_by(verboice_project_id: Setting[:project])
    @report_setting = Setting.report || Setting::ReportSetting.new {}
    @message_template = Setting.message_template || Setting::MessageTemplateSetting.new {}
    @telegram_bot = TelegramBot.instance
  end

  def update_settings
    [:project, :project_variable].each do |key|
      Setting[key] = params[key]
    end

    store_variables
    redirect_to settings_path, notice: 'Setting has been saved'
  end

  def store_variables
    Variable.save_from_params(params)
  end

  def verboice
    response = Service::Verboice.auth(params[:email], params[:password])
    Setting[:verboice_email] = params[:email]
    Setting[:verboice_token] = nil

    if response && response["success"]
      Setting[:verboice_token] = response["auth_token"]
      redirect_to settings_path(tab: Setting::VERBOICE), notice: 'Successfully connected to verboice'
    else
      flash.now[:alert] = 'Could not connect to verboice'
      render :index
    end
  end

  # PUT /hub
  def hub
    # TODO refactoring to Setting[:hub] to store HubSetting Object
    Setting[:hub_url] = params[:url]
    Setting[:hub_email] = params[:email]
    Setting[:hub_password] = params[:password] if params[:password].present?
    Setting[:hub_task_name] = params[:task_name]

    redirect_to settings_path(tab: Setting::HUB), notice: 'Hub connection has been saved'
  end

  # PUT /settings/update_report
  def update_report
    if params[:report].present?
      report_setting = Setting::ReportSetting.new(params[:report])
      report_setting.templates = params[:report][:templates]
      Setting[:report] = report_setting
    end

    redirect_to settings_path(tab: Setting::REPORT), notice: 'Report setting has been saved'
  end

  # PUT /settings/update_message_template
  def update_message_template
    if params[:message_template].present?
      message_template = Setting::MessageTemplateSetting.new(params[:message_template])
      Setting[:message_template] = message_template
    end

    redirect_to settings_path(tab: Setting::TEMPLATE), notice: 'Report setting has been saved'
  end

  # PUT /settings/upsert_telegram_bot
  def upsert_telegram_bot
    @telegram_bot = TelegramBot.instance

    if @telegram_bot.update_attributes(telegram_bot_params)
      redirect_to settings_path(tab: Setting::TELEGRAM_BOT), notice: 'Telegram bot is updated successfully!'
    else
      flash.now[:alert] = 'Fail to configure telegram bot!'
      render :index
    end
  end

  private

  def verboice_parameters
    parameters = { projects: [], project_variables: [] }

    begin
      parameters[:projects] = Service::Verboice.connect(Setting).projects
      parameters[:project_variables] = project_variables(Setting[:project])
      parameters[:project_call_flows] = project_call_flows(Setting[:project])
      parameters[:channels] = Service::Verboice.connect(Setting).channels
    rescue JSON::ParserError
      flash.now.alert = " Failed to fetch some data from verboice"
    end

    parameters
  end

  def project_variables(project_id)
    project_id.present? ? Service::Verboice.connect(Setting).project_variables(project_id) : []
  end

  def project_call_flows project_id
    project_id.present? ? Service::Verboice.connect(Setting).project_call_flows(project_id) : []
  end

  def telegram_bot_params
    params.require(:telegram_bot).permit(:token, :username, :enabled)
  end
end

app/helpers/setting_helper.rb
module SettingHelper
  def tab_active_for(tab)
    active_tab = params[:tab].blank? ? :default : params[:tab].to_sym
    active = ( tab == active_tab ) ? 'active' : ''
    active
  end
end

app/views/settings/_connection.html.erb
<%= form_tag verboice_path, class: 'form form-inline', method: :put do %>
  <div class='input-row'>
    <%= label_tag :email %>
    <%= text_field_tag :email, Setting[:verboice_email], class: 'form-control' %>
  </div>

  <div class='input-row'>
    <%= label_tag :password %>
    <%= password_field_tag :password, '', class: 'form-control', autocomplete: :off %>
  </div>

  <div class='input-row'>
    <label></label>
    <%= button_tag 'Connect', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/settings/_hub.html.erb
<div class="hub panel-head clearfix" style="padding: 10px;">
  <%= form_tag hub_path, class: 'form form-inline', method: :put do %>
    <input type='password' style='display:none;' />
    <div class='input-row'>
      <%= label_tag :url %>
      <%= text_field_tag :url, Setting[:hub_url], class: 'form-control' %>
    </div>

    <div class='input-row'>
      <%= label_tag :email %>
      <%= text_field_tag :email, Setting[:hub_email], class: 'form-control' %>
    </div>

    <div class='input-row'>
      <%= label_tag :password %>
      <%= password_field_tag :password, '', class: 'form-control' %>
    </div>

    <div class='input-row'>
      <%= label_tag :task_name %>
      <%= text_field_tag :task_name, Setting[:hub_task_name], class: 'form-control' %>
    </div>

    <div class='input-row'>
      <label></label>
      <%=button_tag 'Save', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/settings/_nav_bar.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="<%= params[:tab].present? ? tab_active_for(Setting::VERBOICE) : 'active' %>">
    <%= link_to Setting::VERBOICE.to_s.camelcase, settings_path(tab: Setting::VERBOICE) %>
  </li>

  <li role="presentation" class="<%= tab_active_for(Setting::ALERT) %>">
    <%= link_to Setting::ALERT.to_s.camelcase, settings_path(tab: Setting::ALERT) %>
  </li>

  <li role="presentation" class="<%= tab_active_for(Setting::REPORT) %>">
    <%= link_to Setting::REPORT.to_s.camelcase, settings_path(tab: Setting::REPORT) %>
  </li>

  <% if Setting.hub_enabled? %>
    <li role="presentation" class="<%= tab_active_for(Setting::HUB) %>">
      <%= link_to Setting::HUB.to_s.camelcase, settings_path(tab: Setting::HUB) %>
    </li>
  <% end %>

  <li role="presentation" class="<%= tab_active_for(Setting::TEMPLATE) %>">
    <%= link_to Setting::TEMPLATE.to_s.camelcase, settings_path(tab: Setting::TEMPLATE) %>
  </li>

  <li role="presentation" class="<%= tab_active_for(Setting::TELEGRAM_BOT) %>">
    <%= link_to Setting::TELEGRAM_BOT.to_s.camelcase, settings_path(tab: Setting::TELEGRAM_BOT) %>
  </li>
</ul>

app/views/settings/_notify_report_reviewed.erb
<div class="alert-section" style="width: 620px;">
  <div class="panel-head clearfix" style="padding: 10px;">

    <%= simple_form_for @report_reviewed_setting, html: { class: 'form-inline form alert-form'} do |f| %>
      <%= f.input :endpoint, label: 'End point', class: 'form-control' %>
      <%= f.input :username, label: 'Username', class: 'form-control' %>
      <%= f.input :password, label: 'Password', class: 'form-control' %>

      <div class='form-group'>
        <label class="control-label">&nbsp;</label>
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      </div>

    <% end %>

  </div>
</div>

app/views/settings/_report.html.erb
<div class='report' style='width: 650px;'>
  <div class='panel-head clearfix' style='padding: 10px;'>
    <%= form_tag update_report_settings_path, class: 'form form-inline alert-form', method: :put do %>

      <div class='form-group clearfix'>
        <label class='control-label left'>Alert on </label>
        <div>
          <% Calendar.weekdays.each do |k, v| %>
            <%= check_box_tag 'report[days][]', k, @report_setting.has_day?(k) %>
            <%= v[:short_name] %>
          <% end %>
        </div>
      </div>

      <div class='form-group clearfix'>
        <label class='control-label left'>When health center missing report </label>
        <div>
          <%= number_field_tag 'report[x_week]', @report_setting.try(:x_week), min: 1, max: 10 %>
          <span> week(s)</label>
        </div>
      </div>

      <div class='form-group clearfix'>
        <label class='control-label left'>Recipient(s)</label>
        <div class='horizontal-form-control'>
          <% Place::Type.all.each do |place_type| %>
            <div>
              <% if @report_setting && @report_setting.recipient_types.include?(place_type[:code]) %>
                <input name='report[recipient_types][]' value="<%= place_type[:code] %>" type='checkbox' class='ace' checked='checked' />
              <% else %>
                <input name='report[recipient_types][]' value="<%= place_type[:code] %>" type='checkbox' class='ace' />
              <% end %>
              <span class='lbl'> <%= place_type[:display_name] %></span>
            </div>
          <% end %>
          <input name='report[recipient_types][]' type='hidden' />
        </div>
      </div>

      <%= render 'settings/index/report_sms'%>
      <%= render 'settings/index/report_telegram'%>
      <%= render 'settings/index/report_voice'%>

      <!-- Action button -->
      <div class='form-group clearfix'>
        <label class='control-label'>&nbsp;</label>
        <%= submit_tag 'Save', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/settings/_telegram_bot.html.erb
<div class="alert-section" style="width: 620px;">
  <div class="panel-head clearfix" style="padding: 10px;">
    <!-- Title -->
    <div class='d-flex align-items-center'>
      <h4 style="margin-right: 10px;">Telegram notification</h4>

      <% if @telegram_bot.present? && @telegram_bot.enabled? && @telegram_bot.actived? %>
        <i class="fa fa-check-circle text-success" data-toggle="tooltip" title='Valid bot and turn on'></i>
      <% else %>
        <i class="fa fa-times-circle text-danger" data-toggle="tooltip" title='Invalid or turn off bot'></i>
      <% end %>

      <%= link_to 'Need help?', help_path, class: 'btn btn-link' %>
    </div>

    <!-- Form -->
    <%= simple_form_for @telegram_bot, url: 'upsert_telegram_bot', method: :put, html: { class: 'form-inline form alert-form'} do |f| %>

      <!-- Enable Notification -->
      <div class="form-group">
        <label class="control-label">Enable notification?</label>
        <div>
            <%=f.check_box :enabled, class: 'form-control ace ace-switch ace-switch-4 btn-empty' %>
            <span class="lbl" style="vertical-align:bottom"></span>
        </div>
      </div>



      <!-- Token -->
      <div class="form-group">
        <label class="control-label">Token</label>
        <div>
          <%= f.input :token, label: false %>
        </div>
      </div>

      <!-- Username -->
      <div class="form-group">
        <label class="control-label">User name</label>
        <div>
          <%= f.input :username, label: false %>
        </div>
      </div>

      <!-- Action button -->
      <div class='form-group'>
        <label class="control-label">&nbsp;</label>
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/settings/_variable.html.erb
<% clazz = variable.disabled ? 'grey' : '' %>

<div class="panel panel-default panel-variable <%= clazz %>" style="width: 600px;">
  <div class="panel-head clearfix" style="padding: 10px; background: #d0d0d0;">
    <% if variable.new_record? %>
       <div class="pull-left"> Add new variable mapping </div>
       <div class="pull-right">
         <%= link_to '#', class:'variable-collapsable' do %>
           <i class='icon glyphicon glyphicon-plus'> </i>
         <% end %>
       </div>
    <% else %>
       <div class="pull-left">
          <%= variable.name %>
          <i class='glyphicon glyphicon-link'> </i>
          <%= variable.verboice_name %>
          <% if variable.disabled %>
            <i class="glyphicon glyphicon glyphicon-eye-close" aria-hidden="true"> </i>
          <% end %>
       </div>
       <div class='pull-right'>
         <%= link_to '#', class: 'variable-collapsable' do %>
           <i class='icon glyphicon glyphicon-pencil'> </i>
         <% end %>

         <%= link_to variable_path(variable), method: :delete, data: {confirm: 'Are you sure you want to delete this variable'} do %>
           <i class='icon glyphicon glyphicon-trash'> </i>
         <% end %>
       </div>
    <% end %>
  </div>

  <div class="panel-body variable-form" style='border-top: 1px solid #eee; border-bottom: 1px solid #eee; display:none;'>
    <%= simple_form_for variable do |f| %>
      <div class='alert alert-danger error-message' style="display:none;"> ffff</div>
      <div class="clearfix">
          <div class="pull-left" style='width: 30%; padding: 10px;'>
            <%= f.input :name, label: 'Variable name', class: 'form-control s-width' %>
          </div>

          <div class="pull-left" style='width: 5%; padding: 20px; padding-left: 5px; margin-top: 20px;' >
            <i class='glyphicon glyphicon-link'> </i>
          </div>

          <div style='width: 35%; padding: 10px;' class="pull-left">
            <%= f.hidden_field :verboice_name, class: 'verboice-variable-name' %>
            <%= f.label :verboice_id, 'Verboice variable' %>
            <%= f.select :verboice_id,
                       project_variables.map{|p| [ p['name'], p['id'] ] },
                       {include_blank: 'Select variable'},
                       {class: 'form-control s-width verboice-variable-id' } %>
          </div>

          <div class="pull-left" style='width: 30%; padding: 10px;'>
            <%= f.input :dhis2_data_element_uuid, label: "CamEwarn's UUID", class: 'form-control s-width' %>
          </div>
      </div>

      <div class="clearfix">
        <div class="pull-left" style='width: 35%; padding: 10px;'>
          <%= f.input :background_color, label: 'Header background color', as: :minicolors, input_html: {data: {
        minicolors: {theme: :bootstrap,defaultValue: '#f3f3f3', position: :right}}} %>
        </div>
        <div class="pull-left" style='width: 35%; padding: 10px;'>
          <%= f.input :text_color, label: 'Text column color', as: :minicolors, input_html: {data: {
        minicolors: {theme: :bootstrap,defaultValue: '#000000', position: :right}}} %>
        </div>
      </div>

      <div class='form-group clearfix' style='padding: 10px;'>
        <label class='control-label left'>Hide from Report</label>
        <div class='horizontal-form-control'>
          <%= f.check_box :disabled, class: 'form-control ace ace-switch ace-switch-4 btn-empty', input_html: { 'data-toggle' => 'toggle' } %>
          <span class='lbl' style='vertical-align:bottom'></span>
        </div>
      </div>

      <div class="clearfix">
        <div class="vertical-checkbox-list" style="padding: 10px;">
          <label>Apply alert setting</label>
          <% Variable::ALERT_METHODS.each do |key, method| %>
            <div style="border-bottom:none">
              <%= f.radio_button :alert_method, key, class: 'alert_method' %>
              <span class="lbl"><%= method.html_safe %></span>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-action" style="text-align: right; margin-top: 15px;">
        <button type='reset' class="btn btn-default hide-variable-form" > Cancel </button>
        <button type="button" class="btn btn-primary save-varialble"> Save </button>
      </div>
    <% end %>
  </div>
</div>

app/views/settings/_variable_form.html.erb
<% clazz = variable.disabled ? 'grey' : '' %>

<div class="panel panel-default panel-variable <%= clazz %>" style="width: 600px;">

  <div class="panel-body variable-form" style='border-top: 1px solid #eee; border-bottom: 1px solid #eee; display:none;'>
    <%= simple_form_for variable do |f| %>
      <div class='alert alert-danger error-message' style="display:none;"> ffff</div>
      <div class="clearfix">
        <div class="pull-left" style='width: 30%; padding: 10px;'>
          <%= f.input :name, label: 'Variable name', class: 'form-control s-width' %>
        </div>

        <div class="pull-left" style='width: 5%; padding: 20px; padding-left: 5px; margin-top: 20px;' >
          <i class='glyphicon glyphicon-link'> </i>
        </div>

        <div style='width: 35%; padding: 10px;' class="pull-left">
          <%= f.hidden_field :verboice_name, class: 'verboice-variable-name' %>
          <%= f.label :verboice_id, 'Verboice variable' %>
          <%= f.select :verboice_id,
                     project_variables.map{|p| [ p['name'], p['id'] ] },
                     {include_blank: 'Select variable'},
                     {class: 'form-control s-width verboice-variable-id' } %>
        </div>
        <% if Setting.hub_enabled? %>
          <div class="pull-left" style='width: 30%; padding: 10px;'>
            <%= f.input :dhis2_data_element_uuid, label: "CamEwarn's UUID", class: 'form-control s-width' %>
          </div>
        <% end %>
      </div>

      <div class="clearfix">
        <div class="pull-left" style='width: 35%; padding: 10px;'>
          <%= f.input :background_color, label: 'Header background color', as: :minicolors, input_html: {data: {
        minicolors: {theme: :bootstrap,defaultValue: '#f3f3f3', position: :right}}} %>
        </div>
        <div class="pull-left" style='width: 35%; padding: 10px;'>
          <%= f.input :text_color, label: 'Text column color', as: :minicolors, input_html: {data: {
        minicolors: {theme: :bootstrap,defaultValue: '#000000', position: :right}}} %>
        </div>
      </div>

      <div class='form-group clearfix' style='padding: 10px;'>
        <label class='control-label left'>Hide from Report</label>
        <div class='horizontal-form-control'>
          <%= f.check_box :disabled, class: 'form-control ace ace-switch ace-switch-4 btn-empty', input_html: { 'data-toggle' => 'toggle' } %>
          <span class='lbl' style='vertical-align:bottom'></span>
        </div>
      </div>

      <div class="clearfix">
        <div class="vertical-checkbox-list" style="padding: 10px;">
          <label>Apply alert setting</label>
          <% Variable::ALERT_METHODS.each do |key, method| %>
            <div style="border-bottom:none">
              <%= f.radio_button :alert_method, key, class: 'alert_method' %>
              <span class="lbl"><%= method.html_safe %></span>
              <% if key == :case_base %>
                <% if variable.alert_method == 'case_base' %>
                  <input style="width: 60px; display: inline-block" class="numeric integer variable_alert"
                  type="number" step="1" value="<%= variable.threshold_value %>" name="variable[threshold_value]" id="variable_threshold_value">
                <% else %>
                  <input style="width: 60px; display: inline-block" class="numeric integer variable_alert"
                type="number" step="1" name="variable[threshold_value]" id="variable_threshold_value" disabled='disabled'>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-action" style="text-align: right; margin-top: 15px;">
        <button type='reset' class="btn btn-default hide-variable-form" > Cancel </button>
        <button type="button" class="btn btn-primary save-varialble"> Save </button>
      </div>
    <% end %>
  </div>

  <div class="panel-head clearfix" style="padding: 10px; background: #d0d0d0;">
    <% if variable.new_record? %>
       <div class="pull-left"> Add new variable mapping </div>
       <div class="pull-right">
         <%= link_to '#', class:'variable-collapsable' do %>
           <i class='icon glyphicon glyphicon-plus'> </i>
         <% end %>
       </div>
    <% else %>
       <div class="pull-left">
          <%= variable.name %>
          <i class='glyphicon glyphicon-link'> </i>
          <%= variable.verboice_name %>
          <% if variable.disabled %>
            <i class="glyphicon glyphicon glyphicon-eye-close" aria-hidden="true"> </i>
          <% end %>
       </div>
       <div class='pull-right'>
         <%= link_to '#', class: 'variable-collapsable' do %>
           <i class='icon glyphicon glyphicon-pencil'> </i>
         <% end %>

         <%= link_to variable_path(variable), method: :delete, data: {confirm: 'Are you sure you want to delete this variable'} do %>
           <i class='icon glyphicon glyphicon-trash'> </i>
         <% end %>
       </div>
    <% end %>
  </div>
</div>

app/views/settings/_verboice_connection_form.html.erb
<%= form_tag verboice_path, class: 'form form-inline', method: :put do %>
  <div class='input-row'>
    <%= label_tag :email %>
    <%= text_field_tag :email, Setting[:verboice_email], class: 'form-control' %>
  </div>

  <div class='input-row'>
    <%= label_tag :password %>
    <%= password_field_tag :password, '', class: 'form-control', autocomplete: :off %>
  </div>

  <div class='input-row'>
    <label></label>
    <%= button_tag 'Connect', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/settings/alert_case.html.erb
<%= breadcrumb [ {"Settings" => nil} ] %>
<div class="tabbable">
	<ul id="myTab" class="nav nav-tabs">
		<li>
      <%= link_to 'Verboice', settings_path%>
		</li>
		<li class="active">
			<%= link_to 'Alert', alert_path, id: 'alert', html: {'data-toggle'=> 'tab'}%>
		</li>
	</ul>

	<div class="tab-content">
		<div class="tab-pane fade in active" id="alert">
      <%= render "alert" %>
		</div>
	</div>
</div>