config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:index, :new, :create, :destroy]
  resources :event_attachments, only: [] do
    member do
      get :download
    end
  end

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'reports#index'

  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :sessions, only: [:index, :create, :destroy]
  resources :verboice_callbacks, only: [:index]
  resources :dashboards, only: [:index]
  resources :calendars, only: [:index]
  resources :weeks, only: [:index]
  resources :sms_recipients
  resources :places do
    collection do
      get 'ods_list'
      get 'download_template'
      post 'confirm_upload_location'
      post 'upload_location'
      get 'import'
      get 'download'
      get 'download_users'
    end
    member do
      put 'move'
    end
  end

  resources :users do
    collection do
      get 'profile'
      put 'change_profile'
      get 'download_template'
      post 'confirmed_upload_users'
      post 'upload_users'
      get 'by_place'
      get 'search'
      get 'import'
    end

    member do
      put 'reset'
    end
  end

  resources :settings, only: [:index] do
    collection do
      put 'update_report'
    end
  end

  put 'message_template' => 'settings#update_message_template'
  put 'update_settings' => 'settings#update_settings'
  put 'upsert_telegram_bot' => 'settings#upsert_telegram_bot'

  put 'verboice' => 'settings#verboice'
  put 'hub' => 'settings#hub'
  get 'project_variables' => 'settings#project_variables'
  get 'external' => 'settings#external'

  get '/steps/manifest' => 'steps#manifest', defaults: { format: :xml }
  resources :steps do
    collection do
      post :validate_hc_worker
      post :send_sms
      post :notify_reporting_started
      post :notify_reporting_ended
    end
  end

  resources :reports, only: [:index, :destroy] do
    member do
      put :toggle_status
      put :update_week
    end

    collection do
      get :export_as_csv
      get :query_piechart
    end
  end

  resources :report_variables, only: [] do
    member do
      get :play_audio
    end
  end

  resources :variables

  resources :channels do
    member do
      put 'state'
      put 'mark_as_default'
    end
  end

  resources :logs, only: [:index]

  resources :alert_settings

  resources :external_sms_settings
  resources :hub_push_notifications, only: [:create]

  resources :sms_broadcasts, only: [:index, :create]

  resources :weekly_place_reports, only: [:index]

  namespace :api, defaults: {format: 'json'} do
    resources :places, only: [:index]
    namespace :hub do
      resources :reports, only: [:index, :show]
    end
  end

  # Telegram
  telegram_webhook TelegramWebhooksController
  resource :help, only: [:show]
end

app/controllers/import_users_controller.rb
class ImportUsersController < ApplicationController

  def new

  end

  def create
    csv_string = File.read(params[:user].path, :encoding => 'utf-8')
    users = UserCSV.new(csv_string).import
    render :json => users, :root => false
  end

  def decode
    csv_string = File.read(params[:user].path, :encoding => 'utf-8')
    users = UserCSV.new(csv_string).decode
    render :json => users, :root => false
  end

  def template
    respond_to do |format|
      format.json  { render :json => result }
      format.csv {
        render :text => UserCSV.sample
      }
    end
  end

end

app/views/import_users/new.html.erb
<%= breadcrumb [ {"Health Structure" => places_path()}, {"Import user" => nil}] %>
<div class="fuelux-wizard-container">
  <!-- #section:plugins/fuelux.wizard.steps -->
  <ul class="steps">
    <li data-step="1">
      <span class="step"><%= link_to "1", places_import_path() %></span>
      <span class="title">Import Place</span>
    </li>

    <li data-step="2" class="active">
      <span class="step">
        <%= link_to "2", users_import_path() %>
      </span>
      <span class="title">Import User</span>
    </li>
  </ul>

  <hr>

  <div class="col-sm-12 widget-container-col ui-sortable">
    <!-- #section:custom/widget-box.options.transparent -->
    <div class="widget-box transparent ui-sortable-handle">
      <div class="widget-header">
        <h4 class="widget-title strong">Import user</h4>

        <div class="widget-toolbar no-border">
          <a data-action="settings" href="#">
            <i class="ace-icon fa fa-cog"></i>
          </a>

          <a data-action="reload" href="#">
            <i class="ace-icon fa fa-refresh"></i>
          </a>

          <a data-action="collapse" href="#">
            <i class="ace-icon fa fa-chevron-up"></i>
          </a>

          <a data-action="close" href="#">
            <i class="ace-icon fa fa-times"></i>
          </a>
        </div>
      </div>

      <div class="widget-body">
        <div class="widget-main padding-10 no-padding-left no-padding-right">
          <p> This tool allows you to import a bunch of users to your system by using a <%= link_to raw("user form"), users_template_path + ".csv", :method => :get, :class => 'bold_link', :format => :csv %> as a template. </p>
        </div>
      </div>
      <div class="widget-main">
        <div class="form-group">
          <div class="col-xs-6">

            <label class="ace-file-input">
              <form id="import-user" method="POST" target="uploadUser" enctype="multipart/form-data">
                <input type="file" class="file-input" id="user-file-select"  name="files[]" >
              </form>
            </label>

            <iframe id="uploadUser" name="uploadUser" height="0" width="0" frameborder="0" scrolling="yes"></iframe>

          </div>
        </div>

        <!-- /section:custom/file-input.filter -->
      </div>
      <div class='tmp-wrapper' id="myTmpTree" style="display:none;">
        <br />
        <div class="table-header">
          Preview for "Latest Uploaded User"
        </div>
        <div id="dynamic-table_wrapper" class="dataTables_wrapper form-inline no-footer">
          <table class="table table-striped table-bordered table-hover" id="errors-table">
            <thead>
              <tr>
                <th>Login</th>
                <th>Full Name</th>
                <th class="hidden-480">Email</th>

                <th>
                  <i class="ace-icon fa fa-clock-o bigger-110 hidden-480"></i>
                  Phone Number
                </th>
                <th class="hidden-480">Place</th>
                <th>Status</th>
                <th>Detail</th>
              </tr>
            </thead>
            <tbody id="tbody">
            </tbody>
          </table>
        </div>
        <button class="btn btn-success" id="btn-import-user"> Confirm Import</button>
      </div>
        <!-- /section:custom/widget-box.options.transparent -->
    </div>
  </div>
</div>