config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:index, :new, :create, :destroy]
  resources :event_attachments, only: [] do
    member do
      get :download
    end
  end

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'reports#index'

  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :sessions, only: [:index, :create, :destroy]
  resources :verboice_callbacks, only: [:index]
  resources :dashboards, only: [:index]
  resources :calendars, only: [:index]
  resources :weeks, only: [:index]
  resources :sms_recipients
  resources :places do
    collection do
      get 'ods_list'
      get 'download_template'
      post 'confirm_upload_location'
      post 'upload_location'
      get 'import'
      get 'download'
      get 'download_users'
    end
    member do
      put 'move'
    end
  end

  resources :users do
    collection do
      get 'profile'
      put 'change_profile'
      get 'download_template'
      post 'confirmed_upload_users'
      post 'upload_users'
      get 'by_place'
      get 'search'
      get 'import'
    end

    member do
      put 'reset'
    end
  end

  resources :settings, only: [:index] do
    collection do
      put 'update_report'
    end
  end

  put 'message_template' => 'settings#update_message_template'
  put 'update_settings' => 'settings#update_settings'
  put 'upsert_telegram_bot' => 'settings#upsert_telegram_bot'

  put 'verboice' => 'settings#verboice'
  put 'hub' => 'settings#hub'
  get 'project_variables' => 'settings#project_variables'
  get 'external' => 'settings#external'

  get '/steps/manifest' => 'steps#manifest', defaults: { format: :xml }
  resources :steps do
    collection do
      post :validate_hc_worker
      post :send_sms
      post :notify_reporting_started
      post :notify_reporting_ended
    end
  end

  resources :reports, only: [:index, :destroy] do
    member do
      put :toggle_status
      put :update_week
    end

    collection do
      get :export_as_csv
      get :query_piechart
    end
  end

  resources :report_variables, only: [] do
    member do
      get :play_audio
    end
  end

  resources :variables

  resources :channels do
    member do
      put 'state'
      put 'mark_as_default'
    end
  end

  resources :logs, only: [:index]

  resources :alert_settings

  resources :external_sms_settings
  resources :hub_push_notifications, only: [:create]

  resources :sms_broadcasts, only: [:index, :create]

  resources :weekly_place_reports, only: [:index]

  namespace :api, defaults: {format: 'json'} do
    resources :places, only: [:index]
    namespace :hub do
      resources :reports, only: [:index, :show]
    end
  end

  # Telegram
  telegram_webhook TelegramWebhooksController
  resource :help, only: [:show]
end

app/models/concerns/reports/elasticsearch.rb
require 'elasticsearch/model'

module Reports::Elasticsearch
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    index_name Rails.application.class.parent_name.underscore
    document_type self.name.underscore

    def as_indexed_json(options={})
      option = self.as_json(
        include: { user: {only: :username},
                   place: {only: [:name, :code, :kind_of]},
                 })

      option['report_variables'] = []

      self.report_variables.includes(:variable).each do |report_variable|
        option['report_variables'].push(
          {
            verboice_name: report_variable.variable.try(:verboice_name),
            type: report_variable.type,
            value: report_variable.value
          }
        )
      end

      option
    end
  end
end

app/models/concerns/reports/filterable.rb
module Reports::Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    # from=2015-06-29&to=2015-07-14&phd=27&od=30&status=Listened
    def filter options
      reports = self.where('1=1')

      if options[:from].present?
        from = Date.strptime(options[:from], '%Y-%m-%d').to_time
        reports = reports.where(['called_at >= ?', from.beginning_of_day])
      end

      if options[:to].present?
        to = Date.strptime(options[:to], '%Y-%m-%d').to_time
        reports = reports.where(['called_at <= ?', to.end_of_day])
      end

      reports = reports.where(called_at: options[:last_day].to_i.day.ago.to_date..Date.today + 1.day) if options[:last_day].present?
      reports = reports.where(place_id: options[:place_id]) if options[:place_id].present?
      reports = reports.where(phd_id: options[:phd]) if options[:phd].present?
      reports = reports.where(od_id: options[:od]) if options[:od].present?
      reports = reports.where(reviewed: options[:reviewed]) if options[:reviewed].present?
      reports = reports.where(reviewed: true) if options[:state] === Report::REVIEWED

      if options[:week].present?
        week = Calendar::Week.parse(options[:week])
        reports = reports.where(year: week.year.number, week: week.week_number)
      end

      reports = reports.where(year: options[:year]) if options[:year].present? && options[:reviewed].to_i != Report::STATUS_NEW
      reports = reports.where("week >= ?", options[:from_week]) if options[:from_week].present? && options[:reviewed].to_i === Report::STATUS_REVIEWED
      reports = reports.where("week <= ?", options[:to_week]) if options[:to_week].present? && options[:reviewed].to_i === Report::STATUS_REVIEWED

      reports
    end
  end
end

app/models/concerns/reports/observer.rb
module Reports::Observer
  extend ActiveSupport::Concern

  included do
    after_save :notify_report_confirmation_and_alert, if: :finished_with_status_changed?

    def notify_report_confirmation_and_alert
      # report confirmation
      notify_report_confirmation if Setting.message_template && Setting.message_template.enabled?

      # Checking alert
      alert_checking if AlertSetting.has_alert?(self.verboice_project_id)
    end

    def notify_report_confirmation
      # TODO Refactoring to remove alert_setting dependency
      return unless self.has_report_variabled? && Setting.message_template.report_confirmation.present?

      [:sms, :telegram].each do |type|
        AdapterType.for(confirm_alert, type).process
      end
    end

    def confirm_alert
      @confirm_alert ||= Alerts::ReportConfirmationAlert.new(Setting.message_template, self)
    end

    def alert_checking
      # TODO Refactoring
      self.report_variable_values.each do |report_variable|
        report_variable.check_alert_for(self.camewarn_week, self.place) if report_variable.alert_defined?
      end

      self.notify_alert if self.having_alerted_variable?
    end
  end
end

app/controllers/api/hub/reports_controller.rb
module Api::Hub
  class ReportsController < Api::ApiController
    before_filter :authenticate_http_basic

    # GET api/hub/reports
    def index
      reports = [{id: 'FAAS3234', name: 'Weekly Disease Report'}]
      render json: reports, root: false
    end

    # api/hub/reports/:id
    def show
      render json: Variable.applied(Setting[:project])
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  authorize_resource

  before_action :load_user_context, only: [:index, :query_piechart, :export_as_csv]

  helper_method :sort_column, :sort_direction

  def required_admin_role!

  end

  def index
    reports = @user_context.reports.includes(:report_variables, :user, :phd, :od)
                     .effective
                     .filter(params)
    reports = sort_column ? reports.order(sort_column + " " + sort_direction) : reports.order('id DESC')
    @reports = reports.page(params[:page])
    @variables = Variable.applied(Setting[:project])

    @events = EventDecorator.decorate_collection(Event.announcing)
  end

  def query_piechart
    @reports = @user_context.reports
      .includes(:report_variables, :user, :phd, :od)
      .effective
      .filter(params)
      .includes(:phd, :od)
      .order('id DESC')
    data_review = Report.to_piechart_reviewed(@reports)
    data_phd = Report.to_piechart_phd(@reports)
    render :json => {:review => data_review, :phd => data_phd}
  end

  def export_as_csv
    file = ReportCsv.new(@user_context).start(params)
    send_file file, type: "text/csv"
  end

  def toggle_status
    report = Report.find(params[:id])
    authorize! :update, report

    if report.toggle_status
      head :ok
    else
      render nothing: true, status: 400
    end
  end

  def update_week
    report = Report.find(params[:id])
    authorize! :update, report

    week = Calendar::Week.parse(params[:week])

    if report.reviewed_as!(week.year.number, week.week_number)
      head :ok
    else
      render nothing: true, status: :not_found
    end
  end

  def destroy
    @report = Report.find(params[:id])
    authorize! :destroy, @report

    @report.delete_status = true
    if @report.save
      redirect_to request.referrer, notice: 'Report has been deleted successfully'
    else
      redirect_to request.referrer, alert: 'Failed to delete report'
    end
  end

  private

  def load_user_context
    @user_context = UserContext.for(current_user)
  end

  def sort_column
    Report.column_names.include?(params[:sort]) ? params[:sort] : nil
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {from: params[:from], to: params[:to], phd: params[:phd], od: params[:od], reviewed: params[:reviewed], sort: column, direction: direction}, {:class => css_class}
  end
end

app/views/reports/_announcement.html.erb
<% if @events.size > 0 %>
  <div class='panel panel-default'>
    <div class="panel-body" style='padding: 0;'>
      <table class="table no-margin">
        <thead>
          <td style='text-align: left;'>
            Announcement <%= image_tag 'news.gif' %>
          </td>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr class='red'>
              <td colspan="2" style='text-align: left;'>
                <%= event.due_date %>: <%= event.description %>
                <%= link_to event.url_ref, event.url_ref %>
                <% event.attachments.each do |attachment| %>
                  <%= link_to download_event_attachment_path(attachment), class: 'btn btn-xs btn-success' do %>
                    <i class='glyphicon glyphicon-download'> </i> <%= attachment.filename %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/reports/_filter.html.erb
<script>
  fromWeek = '<%= params[:from_week] %>';
  toWeek = '<%= params[:to_week] %>';
  currentYear = '<%= params[:year].present? ? params[:year] : Time.now.year %>';
</script>

<% year = params[:year].present? ? params[:year].to_i : Time.now.year %>

<div class='panel panel-default'>
  <div class='panel-heading'>
    <h3 class='panel-title'>Filter</h3>
  </div>

  <div class="panel-body" style='padding: 10px 0px;'>
    <%= form_tag reports_path, method: 'GET' do |f| %>
      <%= hidden_field_tag :state, params[:state] %>

      <% if params[:state] === Report::NEW %>
        <%= hidden_field_tag :last_day, Report::DEFALUT_DISLAY_IN_LAST_DAY %>
      <% end %>

      <div class='input-row col-lg-2'>
        <%= label_tag :reviewed, 'Reviewed Status' %>
        <%= select_tag :reviewed, options_for_select([[ "Reviewed", 1], ["New", 0]], params[:reviewed]),
                       class: 'form-control', include_blank: "All" %>
      </div>

      <div class='input-row col-lg-2 year' style="display: none;">
        <%= label_tag :year, 'Period' %>
        <%= select_tag :year, options_for_select(Calendar::Year.new(Time.now.year).near_by(2), year),
                       class: 'form-control' %>
      </div>

      <div class='input-row col-lg-2 from-week-group' style='display: none;'>
        <label>From</label>
        <%= select_tag :from_week, options_for_select(Calendar::Year.new(year).available_weeks.map { |w| [w.display(Calendar::Week::DISPLAY_ADVANCED_MODE), w.week_number]}, params[:from_week]), class: 'form-control', include_blank: 'All' %>
      </div>
      <div class='input-row col-lg-2 to-week-group' style='display: none;'>
        <label>To</label>
        <%= select_tag :to_week, options_for_select(Calendar::Year.new(year).available_weeks.map { |w| [w.display(Calendar::Week::DISPLAY_ADVANCED_MODE), w.week_number]}, params[:to_week]), class: 'form-control', include_blank: 'All' %>
      </div>

      <div class='input-row col-lg-2'>
        <%= label_tag :phd, 'PHD' %>
        <%= select_tag :phd, options_for_select(UserContext.for(current_user).phds_list, params[:phd]),
                       class: 'form-control', include_blank: 'All' %>
      </div>

      <div class='input-row col-lg-2'>
        <%= label_tag :od, 'OD' %>
        <%= select_tag :od, options_for_select(UserContext.for(current_user).ods_list(params[:phd]), params[:od]), class: 'form-control', prompt: "All" %>
      </div>

      <div class='input-row col-lg-2'>
        <button class='btn btn-primary' style='margin-top: 25px;'>
          <i class='glyphicon glyphicon-search'> </i> Filter
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/_modal.html.erb
<!-- set up the modal to start hidden and fade in and out -->
<div id="hubModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- dialog body -->
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        Are you sure you want to submit report to CamEwarn?
      </div>
      <!-- dialog buttons -->

      <div class="modal-footer">
        <button id="hubOK" type="button" class="btn btn-primary">OK</button>
        <button id="hubCancel" type="button" class="btn btn-default">Cancel</button>
      </div>
    </div>
  </div>
</div>

app/views/reports/_table.html.erb
<div class="clearfix">
  <div class="pull-left">
    <h2 class="header-title">List of report</h2>
  </div>
  <div class="pull-right" style='margin-top: 10px;'>
    <%=link_to export_as_csv_reports_path(request.query_parameters), class: 'btn btn-primary' do %>
     <i class="glyphicon glyphicon-upload"> </i> Export as CSV
    <% end %>
  </div>
</div>

<ul class="nav nav-tabs">
  <li role="presentation" class="<%= params[:state] === Report::NEW ? 'active' : '' %>"><%= link_to Report::NEW.camelcase, reports_path(state: Report::NEW, last_day: Report::DEFALUT_DISLAY_IN_LAST_DAY) %></li>
  <li role="presentation" class="<%= params[:state] === Report::REVIEWED ? 'active' : '' %>"><%= link_to Report::REVIEWED.camelcase, reports_path(state: Report::REVIEWED) %></li>
  <li role="presentation" class="<%= params[:state].present? ? '' : 'active' %>"><%= link_to 'All', reports_path %></li>
</ul>

<% if params[:state] === Report::NEW %>
  <div class="clearfix">
    <div class="pull-left">
      <h2 class="header-title">
        in last <%= select_tag 'report_last_day', options_for_select(1..7, params[:last_day]), class: 'report-last-day' %> day(s)
      </h2>
    </div>
  </div>
<% end %>

<div class="table-responsive">
  <table class="report table table-striped table-bordered table-hover">
    <thead>
    <tr style="color: black">
        <td>Reported date</td>
        <td>PHD</td>
        <td>OD</td>
        <td><%= sortable "user_id", "HC" %></td>
        <td>Phone</td>
        <td>Duration<br/>(second)</td>
        <% @variables.each do |variable| %>
          <% unless variable.disabled %>
            <td style="width:150px; background-color: <%= variable.background_color%>;" ><%= variable.name %></td>
          <% end %>
        <% end %>
        <td>Reviewed and assigned</td>
        <td>Action</td>
      </tr>
    </thead>

    <tbody>
      <% if @reports.size > 0 %>
        <tr style="font-weight: bold;">
          <td colspan='6' style='text-align:right;'>Total</td>
          <% @variables.each do |variable| %>
            <% unless variable.disabled %>
              <td style='color: <%= variable.text_color%>;'><%= variable.total_report_value(@reports.map(&:id)) %></td>
            <% end %>
          <% end -%>
          <td></td>
          <td></td>
        </tr>
        <% @reports.each_with_index do |report, index| %>
          <tr>
            <td> <%= report.called_at.strftime(Report::DEFAULT_DISPLAY_DATE_FORMAT) %></td>
            <td>
                <%= link_to(report.phd.name, users_path(place_id: report.phd.try(:id))) if current_user.admin? && report.phd %>
                <%= report.phd.try(:name) if current_user.normal? %>
            </td>
            <td>
               <%= link_to(report.od.name, users_path(place_id: report.od.try(:id))) if current_user.admin? && report.od %>
               <%= report.od.try(:name) if current_user.normal? %>
            </td>
            <td>
              <%= report.user.try(:name)%>
              <%= hidden_field_tag "place_report_#{report.id}", report.try(:place_id) %>
            </td>
            <td>
              <a class='circle' style='border: 1px solid #f3f3f3;
                background-color: <%= report.status_info[:color] %>' data-toggle='tooltip' data-placement=right' title='<%= report.status_info[:text] %>'>
              </a>
              <%= report.phone %>
            </td>
            <td> <%= report.duration%> </td>
            <% @variables.each do |variable| %>
              <% unless variable.disabled %>
                <td style='color: <%= variable.text_color%>;'>
                  <% report_variable = report.report_variables.select{|report_variable| report_variable.variable_id == variable.id}.first %>

                  <div style="position: relative">
                    <% if report_variable && report_variable.is_alerted %>
                      <%= image_tag 'warning.gif', style: 'top:0; right: 0; position: absolute' %>
                    <% end %>
                    <%= display_report_variable(report_variable) %>
                  </div>
                </td>
              <% end %>
            <% end %>

            <td>
              <% if report.dhis2_submitted %>
                <%= Calendar::Year.new(report.year).week(report.week).display %>
              <% else %>
                <%= select_tag(report.id, options_for_select(Calendar::Week.last_of(report.created_at.to_date, Setting.number_of_revise_week_available).map { |w| w.display }, Calendar::Year.new(report.year).week(report.week).display), { include_blank: true, class: 'weekly-report' }) %>
              <% end %>
            </td>

            <td>
              <% if Setting.hub_enabled? %>
                <div style='width: 180px;'>
              <% else %>
                <div>
              <% end %>
              <% if Setting.hub_enabled? && report.reviewed? %>
                <% if report.dhis2_submitted %>
                  <span class='green'><i class='glyphicon glyphicon-ok green'> </i> CamEwarn submitted on <%= report.dhis2_submitted_at.strftime(Report::DEFAULT_DISPLAY_DATE_FORMAT) %></span>
                <% else %>
                  <%= button_tag 'Submit to CamEwarn', data: { id: report.id }, style: 'width: 150px;', class: 'hub btn-success' %>
                <% end %>
              <% end %>

              <% unless report.dhis2_submitted %>
                <%= link_to report_path(report), method: :delete, data: {confirm: 'Are you sure to delete ?'} do %>
                    <i class='glyphicon glyphicon-trash red'> </i>
                <% end %>
              <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      <% else %>
        <td colspan="<%= (8 + @variables.size) %>">
          <div class="alert alert-danger center" style="margin-bottom: 0px">
            There is no record.
            <br>
          </div>
        </td>
      <% end %>
    </tbody>
  </table>
</div>

<div class="clearfix">
  <%= paginate_for(@reports) %>
</div>

app/views/reports/index.html.erb
<%= breadcrumb [ {"Reports" => nil}] %>
<%= page_title "Call list" %>

<div class="inner-container">
  <%= render 'announcement' %>
  <%= render 'filter' %>
  <%= render 'table' %>
  <%= render 'modal' %>
</div>